// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatWebPortal_Core.Data;

namespace ProjekatWebPortal_Core.Migrations.MigrationWithVesti
{
    [DbContext(typeof(VestiDbContext))]
    [Migration("20220122172909_Initial-WithVesti")]
    partial class InitialWithVesti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjekatWebPortal_Core.Models.TeloVestiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeloVesti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VestId");

                    b.ToTable("TeloVesti");
                });

            modelBuilder.Entity("ProjekatWebPortal_Core.Models.VestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumPostavljanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("KratakOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vesti");
                });

            modelBuilder.Entity("ProjekatWebPortal_Core.Models.TeloVestiModel", b =>
                {
                    b.HasOne("ProjekatWebPortal_Core.Models.VestModel", "VestModel")
                        .WithMany()
                        .HasForeignKey("VestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VestModel");
                });
#pragma warning restore 612, 618
        }
    }
}
